const nome = {
    "Afghanistan": "Afghanistan",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua e Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaigian",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrein",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Bielorussia",
    "Belgium": "Belgio",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia ed Erzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brasile",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Capo Verde",
    "Cambodia": "Cambogia",
    "Cameroon": "Camerun",
    "Canada": "Canada",
    "Central African Republic": "Repubblica Centrafricana",
    "Chad": "Ciad",
    "Chile": "Cile",
    "China": "Cina",
    "Colombia": "Colombia",
    "Comoros": "Comore",
    "CG": "Repubblica del Congo",
    "CD": "Repubblica Democratica del Congo",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croazia",
    "Cuba": "Cuba",
    "Cyprus": "Cipro",
    "Czech Republic": "Repubblica Ceca",
    "Denmark": "Danimarca",
    "Djibouti": "Gibuti",
    "Dominica": "Dominica",
    "Dominican Republic": "Repubblica Dominicana",
    "Ecuador": "Ecuador",
    "Egypt": "Egitto",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Equatoriale",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopia": "Etiopia",
    "Fiji": "Figi",
    "Finland": "Finlandia",
    "France": "Francia",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Germany": "Germania",
    "Ghana": "Ghana",
    "Greece": "Grecia",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Ungheria",
    "Iceland": "Islanda",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Ireland": "Irlanda",
    "Israel": "Israele",
    "Italy": "Italia",
    "Ivory Coast": "Costa d'Avorio",
    "Jamaica": "Giamaica",
    "Japan": "Giappone",
    "Jordan": "Giordania",
    "Kazakhstan": "Kazakistan",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kirghizistan",
    "Laos": "Laos",
    "Latvia": "Lettonia",
    "Lebanon": "Libano",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya": "Libia",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituania",
    "Luxembourg": "Lussemburgo",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malesia",
    "Maldives": "Maldive",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Isole Marshall",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Messico",
    "Micronesia": "Micronesia",
    "Moldova": "Moldavia",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Marocco",
    "Mozambique": "Mozambico",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Paesi Bassi",
    "New Zealand": "Nuova Zelanda",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Korea": "Repubblica Popolare Democratica di Corea (Corea del Nord)",
    "MK": "Macedonia del Nord",
    "Norway": "Norvegia",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Palestine State": "Stato di Palestina",
    "Panama": "Panama",
    "Papua New Guinea": "Papua Nuova Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Perù",
    "Philippines": "Filippine",
    "Poland": "Polonia",
    "Portugal": "Portogallo",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Russia",
    "Rwanda": "Ruanda",
    "Saint Kitts and Nevis": "Saint Kitts e Nevis",
    "Saint Lucia": "Santa Lucia",
    "Saint Vincent and the Grenadines": "Saint Vincent e Grenadine",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "São Tomé e Príncipe",
    "Saudi Arabia": "Arabia Saudita",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Slovakia": "Slovacchia",
    "Slovenia": "Slovenia",
    "Solomon Islands": "Isole Salomone",
    "Somalia": "Somalia",
    "South Africa": "Sudafrica",
    "South Korea": "Corea del Sud",
    "SS": "Sud Sudan",
    "Spain": "Spagna",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Sweden": "Svezia",
    "Switzerland": "Svizzera",
    "Syria": "Siria",
    "Taiwan": "Taiwan",
    "Tajikistan": "Tagikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailandia",
    "Timor-Leste": "Timor Est",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad e Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Turchia",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ucraina",
    "United Arab Emirates": "Emirati Arabi Uniti",
    "United Kingdom": "Regno Unito",
    "United States": "Stati Uniti d'America",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Città del Vaticano",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Western Sahara": "Sahara Occidentale",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
    "XK": "Kosovo"
};

